openapi: 3.1.0
x-stoplight:
  id: iq70vu0l29xg1
x-json-schema-faker:
  locale: es
  min-items: 1
  max-items: 10
  resolve-json-path: true
info:
  title: API DE SERVICIOS GENERALES
  version: '1.0'
  contact:
    name: Dirección General de Sistemas
    email: dgs@uan.edu.mx
    url: 'https://piida.uan.mx'
  description: La API de servicios generales pretende...
  termsOfService: 'https://piida.uan.mx/legal/politica-de-privacidad'
  license:
    name: UAN - DGS. All rights reserved
    url: 'https://piida.uan.mx/legal/politica-de-privacidad'
servers:
  - url: 'https://api-servicios.piida.uan.mx/v1'
    description: Production
  - url: 'https://api-servicios-test.piida.uan.mx/v1'
    description: Stagging
paths:
  /ping:
    get:
      summary: Ping
      operationId: get-ping
      description: Retorna `pong` como mensaje junto con cualquier parámetro que se le haya enviado en la QueryString. Útil para probar la conexión y certificados
      parameters:
        - schema: {}
          in: query
          name: '*'
          description: cualquier parámetro
          allowEmptyValue: true
      responses:
        '200':
          $ref: '#/components/responses/success'
  /rh/plazas:
    get:
      summary: Plazas
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Personal'
              examples:
                example-1:
                  value: 2
                  status: success
                  data:
                    meta:
                      count: 2
                      total: 65536
                      offset: 43
                      limit: 2
                    fields:
                      - no_trab
                      - rfc
                      - curp
                      - appat
                      - apmat
                      - nombres
                      - fecha_nac
                      - sexo
                      - no_empleado
                      - estatus
                      - tipo_empleado
                      - tipo_plaza
                      - id_adscripcion
                      - adscripcion
                    entries:
                      - - 14391
                        - AIRT6710235K5
                        - AIRT671023MDFCRS03
                        - LADRON DE GUEVARA
                        - DE LA TEJERA
                        - ASUNCIÓN MARIA DEL CONSUELO
                        - '1967-10-23'
                        - F
                        - 53255
                        - ACTIVO
                        - CONTRATO
                        - DOCENTE
                        - 360
                        - UNIDAD ACADEMICA DE CIENCIAS QUIMICO BIOLOGICAS Y FARMACEUTICAS
                      - - 14392
                        - TRBA7411235K5
                        - TRBA7411235K5CRS53
                        - DE LA TEJERA
                        - LADRON DE GUEVARA
                        - MARIA CONSUELO
                        - '1967-10-23'
                        - F
                        - 53255
                        - ACTIVO
                        - CONTRATO
                        - DOCENTE
                        - 360
                        - UNIDAD ACADEMICA DE CIENCIAS QUIMICO BIOLOGICAS Y FARMACEUTICAS
      operationId: get-rh-plazas
      description: Devuelve una colección de registros de empleados en estatus `ACTIVO`.
      parameters:
        - schema:
            type: string
          in: query
          description: GET /rh/plazas
          name: get_plazas
  '/rh/plazas/{NO_PLAZA}':
    parameters:
      - schema:
          type: string
        name: NO_PLAZA
        in: path
        required: true
    get:
      summary: Número de Plaza
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Personal'
              examples:
                example-1:
                  value:
                    no_trab: 1
                    rfc: string
                    curp: string
                    appat: string
                    apmat: string
                    nombres: string
                    fecha_nac: '1985-07-23'
                    sexo: M
                    no_empleado: 0
                    estatus: ACTIVO
                    tipo_empleado: BASE
                    tipo_plaza: ADMINISTRATIVO
                    id_adscripcion: 0
                    adscripcion: string
      operationId: get-rh-plazas-id
      description: |-
        Dado un número de plaza, retorna la información básica del empleado y la información básica de la plaza solicitada.

        Solo se podrán consultar empleados con estatus `ACTIVO` o `CONTRATO VENCIDO`, los demás estatus BAJA TEMPORAL o BAJA DEFINITIVA se reportarán como 404 no encontrado.

        El tipo de dato de cada campo devuelto en el objeto data se puede consultar en el anexo DEFINICIÓN DE CAMPOS DE PERSONAL.

        Requiere del scope `rh.empleado:read` activo en el Token de AP
      parameters:
        - schema:
            type: string
          in: query
          name: 'GET rh/plazas/{NO_PLAZA}'
          description: número de plaza
  '/rh/empleados/{codigo_trabajador}':
    parameters:
      - schema:
          type: string
          example: '77787'
        name: codigo_trabajador
        in: path
        required: true
        description: Código de trabajador o RFC
    get:
      summary: Código Trabajador RFC
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Personal'
              examples:
                example-1:
                  value:
                    status: success
                    data:
                      no_trab: 14391
                      rfc: AIRT6710235K5
                      curp: AIRT671023MDFCRS03
                      appat: LADRON DE GUEVARA
                      apmat: DE LA TEJERA
                      nombres: ASUNCIÓN MARIA DEL CONSUELO
                      fecha_nac: '1967-10-23'
                      sexo: F
                      // "email": josezep@uan.edu.mx
                      // "telefono": (311) 103 0265
                      // "titulo": DR.
                      plazas:
                        - no_empleado: 53255
                          estatus: ACTIVO
                          tipo_empleado: BASE
                          tipo_plaza: DOCENTE
                          id_adscripcion: 360
                          adscripcion: UNIDAD ACADEMICA DE CIENCIAS QUIMICO BIOLOGICAS Y FARMACEUTICAS
                        - no_empleado: 53256
                          estatus: ACTIVO
                          tipo_empleado: CONTRATO
                          tipo_plaza: ADMINISTRATIVO
                          id_adscripcion: 397
                          adscripcion: COORDINACION DE ANUIES
        '400':
          description: No encontrado
      operationId: get-rh-empleados
      description: |-
        Dado un código de trabajador o RFC, retorna la información básica del empleado y la información básica de las plazas asociadas a ese empleado.

        Solo se podrán consultar empleados que tengan por lo menos una plaza con estatus `ACTIVO` o `CONTRATO VENCIDO`, los demás estatus `BAJA TEMPORAL` o `BAJA DEFINITIVA` se reportarán como `404 no encontrado`.

        El tipo de dato de cada campo devuelto en el objeto `data` se puede consultar en el anexo
        [DEFINICIÓN DE CAMPOS DE PERSONAL](#DEFINICIÓN-DE-CAMPOS-DE-PERSONAL).

        Requiere del scope `rh.empleado:read` activo en el Token de API.
      parameters:
        - schema:
            type: string
          in: query
          name: 'GET /rh/empleados/{codigo_trabajador}'
          description: empleado código de trabajador
      security:
        - Certificado: []
  /escolar/matriculas:
    get:
      summary: Escolar Matrículas
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alumnos'
              examples:
                example-1:
                  value:
                    status: success
                    data:
                      meta:
                        count: 3
                        total: 65536
                        offset: 25
                        limit: 3
                      fields:
                        - appat
                        - apmat
                        - nombres
                        - curp
                        - sexo
                        - matricula
                        - id_carrera
                        - carrera
                        - nivel
                        - modalidad
                        - periodo
                        - estatus
                      entries:
                        - - JAIME
                          - BECERRA
                          - KEILY YULIANA
                          - JABK060320MNTMCLA3
                          - M
                          - '21016619'
                          - 1913
                          - PREPARATORIA 01
                          - B
                          - 0
                          - AGO2021
                          - A PAGO
                        - - IBARRA
                          - ALCANTARA
                          - CRISTOPHER RAFAEL
                          - IAAC031216HDGBLRA3
                          - H
                          - 16010796L
                          - 6394
                          - COMUNICACIÓN Y MEDIOS
                          - L
                          - 0
                          - AGO2021
                          - INSCRITO
                        - - LUGO
                          - GARCIA
                          - MIRIAM JOCELYN
                          - LUGM820111MDFGRR08
                          - M
                          - '20009067'
                          - 7813
                          - 'DERECHO [Virtual]'
                          - L
                          - 5
                          - AGO2020
                          - INSCRITO
          headers: {}
      operationId: get-escolar-matriculas
      description: 'Devuelve una colección de registros de alumnos con matrículas en estatus `CON RECIB`O, `A PAGO`, `PREINSCRITO`, `INSCRITO`.'
      parameters:
        - schema:
            type: string
          in: query
          name: /escolar/matriculas
          description: escolar matriculas
  '/escolar/matriculas/{MATRICULA}':
    parameters:
      - schema:
          type: string
        name: MATRICULA
        in: path
        required: true
    get:
      summary: 'Escolar matriculas {MATRICULA}'
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alumnos'
              examples:
                example-1:
                  value:
                    appat: string
                    apma: string
                    nombres: string
                    curp: string
                    sexo: string
                    matricula: string
                    id_carrera: 0
                    carrera: string
                    nivel: '''L: Licenciatura o Prof Asoc, B:Bachillerato, P:Posgrado'''
                    modalidad: '''0: Escolarizado, 1: SemiEscolarizado, 5: Virtual (en línea)'''
                    periodo: string
                    estatus: ('ADMITIDO')
            application/xml:
              schema:
                $ref: '#/components/schemas/Alumnos'
              examples:
                example-1:
                  value: |-
                    {
                        "status": "success",
                        "data": {
                            "appat": "JAIME",
                            "apmat": "BECERRA",
                            "nombres": "KEILY YULIANA",
                            "curp": "JABK060320MNTMCLA3",
                            "sexo": "M",
                            "matricula": "21016619",
                            "id_carrera": 1913,
                            "carrera": "PREPARATORIA 01",
                            "nivel": "B",
                            "modalidad": 0,
                            "periodo": "AGO2021",
                            "estatus": "A PAGO"
                            // "email": "josezep@uan.edu.mx",
                            // "telefono": "(311) 103 0265",
                        }
                    }
        '400':
          description: 404 no encontrado
      operationId: get-escolar-matriculas-id
      description: |-
        Dada una matrícula, retorna la información básica del alumno y la información básica de la matrícula solicitada.

        Solo se podrán consultar alumnos con matrícula en estatus `CON RECIBO`, `A PAGO`, `PREINSCRITO`, `INSCRITO`, los demás estatus se reportarán como 404 no encontrado.

        El tipo de dato de cada campo devuelto en el objeto data se puede consultar en el anexo DEFINICIÓN DE CAMPOS DE ALUMNOS.

        Requiere del scope escolar.alumno:read activo en el Token de API.
      parameters:
        - schema:
            type: string
          in: query
          name: 'GET /escolar/matriculas/{MATRICULA}'
          description: ' escolar matrículas MATRICULA'
  '/escolar/alumnos/{CURP}':
    parameters:
      - schema:
          type: string
        name: CURP
        in: path
        required: true
    get:
      summary: Escolar Alumnos CURP
      tags: []
      responses:
        '200':
          description: OK
        '400':
          description: No econtrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alumnos'
              examples:
                example-1:
                  value:
                    status: success
                    data:
                      appat: JAIME
                      apmat: BECERRA
                      nombres: KEILY YULIANA
                      curp: JABK060320MNTMCLA3
                      sexo: M
                      // "email": josezep@uan.edu.mx
                      // "telefono": (311) 103 0265
                      matriculas:
                        - matricula: '21010796'
                          id_carrera: 6394
                          carrera: COMUNICACIÓN Y MEDIOS
                          nivel: L
                          modalidad: 0
                          periodo: AGO2021
                          estatus: INSCRITO
                        - matricula: '20009067'
                          id_carrera: 7813
                          carrera: 'DERECHO [Virtual]'
                          nivel: L
                          modalidad: 5
                          periodo: AGO2020
                          estatus: INSCRITO
      operationId: get-escolar-alumnos-id
      description: |-
        Dada una CURP, retorna la información básica del alumno y la información básica de las matrículas asociadas a ese alumno.

        Solo se podrán consultar alumnos con matrícula en estatus CON RECIBO, A PAGO, PREINSCRITO, INSCRITO, los demás estatus se reportarán como 404 no encontrado.
      parameters:
        - schema:
            type: string
          in: query
          name: 'GET /escolar/alumnos/{CURP}'
          description: ' Escolar alumnos CURP'
components:
  schemas:
    Personal:
      type: object
      x-examples:
        example-1:
          no_trab: 14391
          rfc: AIRT6710235K5
          curp: AIRT671023MDFCRS03
          appat: LADRON DE GUEVARA
          apmat: DE LA TEJERA
          nombres: ASUNCIÓN MARIA DEL CONSUELO
          fecha_nac: '1967-10-23'
          sexo: F
          no_empleado: 53255
          estatus: ACTIVO
          tipo_empleado: CONTRATO
          tipo_plaza: DOCENTE
          id_adscripcion: 360
          adscripcion: UNIDAD ACADEMICA DE CIENCIAS QUIMICO BIOLOGICAS Y FARMACEUTICAS
      title: Personal
      description: Modelo personal
      additionalProperties: false
      examples:
        - no_trab: 14391
          rfc: AIRT6710235K5
          curp: AIRT671023MDFCRS03
          appat: LADRON DE GUEVARA
          apmat: DE LA TEJERA
          nombres: ASUNCIÓN MARIA DEL CONSUELO
          fecha_nac: '1967-10-23'
          sexo: F
          no_empleado: 53255
          estatus: ACTIVO
          tipo_empleado: CONTRATO
          tipo_plaza: DOCENTE
          id_adscripcion: 360
          adscripcion: RECTORIA
      properties:
        no_trab:
          type: integer
          example: 14391
          minimum: 1
          exclusiveMaximum: false
        rfc:
          type: string
          example: AIRT6710235K5
          minLength: 12
          maxLength: 13
          pattern: '^([A-ZÑ]|\&){3,4}[0-9]{2}(0[1-9]|1[0-2])([12][0 -9]|0[1-9]|3[01])[A-Z0-9]{3}$'
        curp:
          type: string
          example: AIRT671023MDFCRS03
          minLength: 18
          maxLength: 18
          pattern: '^[A-Z][AEIOUX][A-Z]{2}[\d]{2}(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])[HM](AS|BC|BS|CC|CS|CH|CL|CM|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[B-DF-HJ-NP-TV-Z]{3}[\dA-Z]\d$'
        appat:
          type: string
          example: LADRON DE GUEVARA
          maxLength: 40
          x-faker: faker.name.lastName()
        apmat:
          type: string
          example: DE LA TEJERA
          maxLength: 40
          x-faker: faker.name.lastName()
        nombres:
          type: string
          example: ASUNCIÓN MARIA DEL CONSUELO
          maxLength: 40
          x-faker: faker.name.firstName()
        fecha_nac:
          type: string
          format: date
          example: '1967-10-23'
          pattern: '^\d{4}-\d{2}-\d{2}'
        sexo:
          type: string
          enum:
            - F
            - M
          example: F
          description: 'F: Femenino M: Masculino'
        no_empleado:
          type: integer
          example: 53255
          minimum: 1
          format: int32
          exclusiveMaximum: 300000
        estatus:
          type: string
          enum:
            - ACTIVO
            - BAJA DEFINITIVA
            - BAJA TEMPORAL
            - CONTRATO VENCIDO
          example: ACTIVO
        tipo_empleado:
          type: string
          enum:
            - BASE
            - CONTRATO
            - JUBILADO
            - EXTERNO
          example: CONTRATO
        tipo_plaza:
          type: string
          enum:
            - ADMINISTRATIVO
            - DOCENTE
          example: DOCENTE
        id_adscripcion:
          type: integer
          example: 360
          format: int32
          exclusiveMaximum: 1100
          minimum: 10
        adscripcion:
          type: string
          example: RECTORIA
          maxLength: 40
        '':
          type: string
      required:
        - no_trab
        - rfc
        - curp
        - appat
        - apmat
        - nombres
        - fecha_nac
        - sexo
        - no_empleado
        - estatus
        - tipo_empleado
        - tipo_plaza
        - id_adscripcion
        - adscripcion
      readOnly: true
    Alumnos:
      type: object
      x-examples:
        example-1:
          appat: string
          apma: string
          nombres: string
          curp: string
          sexo: ('F')
          matricula: string
          id_carrera: integer
          carrera: string
          nivel: ('L')
          modalidad: ' ''0: Escolarizado, 1: SemiEscolarizado, 5: Virtual (en línea)'
          periodo: strings
          estatus: ('ADMITIDO')
      description: Modelo alumnos
      title: Alumnos
      properties:
        appat:
          type: string
        apma:
          type: string
        nombres:
          type: string
        curp:
          type: string
        sexo:
          type: string
          minLength: 1
          maxLength: 1
          enum:
            - '(''F'',''M'')'
          example: 'F:Femenino M:Masculino'
        matricula:
          type: string
        id_carrera:
          type: integer
        carrera:
          type: string
        nivel:
          type: string
          minLength: 1
          maxLength: 1
          enum:
            - L
            - B
            - P
        modalidad:
          type: integer
          example: 0
        periodo:
          type: string
        estatus:
          type: string
          enum:
            - ADMITIDO
            - CON RECIBO
            - PREINSCRITO
            - INSCRITO
            - A PAGO
            - BAJA TEMPORAL
            - EGRESADO
            - BAJA DEFINITIVA
            - CAMBIO DE CARRERA
            - COMPLEMENTO
            - EN TRAMITE
            - EN TRAMITE2
      required:
        - appat
        - apma
        - nombres
        - curp
        - sexo
        - matricula
        - id_carrera
        - carrera
        - nivel
        - modalidad
        - periodo
        - estatus
      examples:
        - appat: string
          apma: string
          nombres: string
          curp: string
          sexo: 'F:Femenino M:Masculino'
          matricula: string
          id_carrera: 0
          carrera: string
          nivel: L
          modalidad: 0
          periodo: string
          estatus: ADMITIDO
    Response:
      type: object
      x-examples:
        example-1:
          status: success
          data:
            param: uno
            message: pong
      properties:
        status:
          type: string
        data:
          type: object
          properties:
            '':
              type: string
      required:
        - status
        - data
      examples:
        - status: string
          data:
            '': string
      title: Response
      description: Modelo response
  securitySchemes:
    Certificado:
      type: http
      scheme: mutual
      description: Usar los certificados expedidos y firmados por la Infraestructura de Clave Pública (PKI) de `iDDi UAN - Cert Authority`.
    Token de API:
      type: http
      scheme: bearer
      description: Toda petición a la API de PiiDA se debe autenticar mediante un `Token de API` enlazado con la aplicación cliente que consume la información.
  responses:
    success:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            x-examples:
              example-1:
                status: success
                data:
                  param: uno
                  message: pong
            properties:
              status:
                type: string
              data:
                type: object
            required:
              - status
              - data
          examples:
            ejemplo-ping:
              value:
                status: success
                data:
                  message: pong
    succes-personal:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            x-examples:
              example-1:
                status: success
                data: {}
            properties:
              status:
                type: string
                default: success
              data:
                $ref: '#/components/schemas/Personal'
            required:
              - status
              - data
          examples:
            example-1:
              value:
                status: success
                data:
                  no_trab: 14391
                  rfc: AIRT6710235K5
                  curp: AIRT671023MDFCRS03
                  appat: LADRON DE GUEVARA
                  apmat: DE LA TEJERA
                  nombres: ASUNCIÓN MARIA DEL CONSUELO
                  fecha_nac: '1967-10-23'
                  sexo: F
                  no_empleado: 53255
                  estatus: ACTIVO
                  tipo_empleado: CONTRATO
                  tipo_plaza: DOCENTE
                  id_adscripcion: 360
                  adscripcion: RECTORIA
    succes-alumnos:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
              data:
                $ref: '#/components/schemas/Alumnos'
          examples:
            example-1:
              value:
                status: string
                data:
                  appat: string
                  apma: string
                  nombres: string
                  curp: string
                  sexo: 'F:Femenino M:Masculino'
                  matricula: string
                  id_carrera: 0
                  carrera: string
                  nivel: L
                  modalidad: 0
                  periodo: string
                  estatus: ADMITIDO
                  // "email": josezep@uan.edu.mx
                  // "telefono": (311) 103 0265
security:
  - Token de API: []
